### PR TITLE
Add Sphinx documentation

### PR DESCRIPTION
**Pull request by ZedThree**
(This includes #26, so the PR diff will be larger than expected till that's merged. Changes here start from 03de75dcfc4affb7562547bf548d12ce4bb42a15)

Adds the basic structure for automated docs building. This will still need setting up on ReadTheDocs, but we should probably have a little chat about that first.

To view the docs locally:

```
# Install all the docs-related packages
pip install -e .[docs]
cd docs
make html
# Open docs/_build/html/index.html in your browser
```

The docs landing page is `docs/index.rst`. I've moved all the notebooks to `docs/examples` so they can be rendered as part of the docs. I've tidied them up a fair bit to make their main points clearer, including changing some of the colourmaps (see the [Matplotlib explainer](https://matplotlib.org/3.5.3/tutorials/colors/colormaps.html), including references, on choices of colourmaps). This mostly affects examples 3 and 5, so you might want to double check those in particular.

This PR also adds type hints to lots of functions, to help the docs, though I've not gone through and made sure everything's consistent yet. That will probably have to wait till I look at using dataclasses to replace the dicts, etc.

The other big change is that I've renamed the `LRBv21` function to `run_dls`. This was because importing `LRBv21.LRBv21` at the top level hides the `LRBv21` module, so none of the docs in there were getting rendered. I think `run_dls` is probably a fairly reasonable name.

### CODE REVIEW

**Comment by mikekryjak** [comment]
The new colormap for the 2D plots is awesome! Sorry I haven't gotten to reviewing all this yet, been stuck on the interview prep.

**Review by mikekryjak — COMMENTED** [review]
What's uv for?

**Comment by ZedThree** [comment]
`uv` is an alternative to `pip` that's much, much faster: https://github.com/astral-sh/uv

I was trying it out the Github CI, but ended up not using it.

I've just merged in `main`, so the diff in this PR now only has the interesting changes!

**Review by mikekryjak — APPROVED** [review]
Compiles fine and works great!

**Pull request merged**
