### PR TITLE
Fix lots of linting warnings, various minor tidying

### PR DESCRIPTION
**Pull request by ZedThree**
Fix warnings and errors from `ruff`

(Includes both #32 and #28 )

### CODE REVIEW

**Comment by mikekryjak** [comment]
@ZedThree the other branches are merged now, I'll wait until you merge master into this before I go through it properly.

**Comment by ZedThree** [comment]
Oops, I was using an older version of `ruff` locally, so didn't catch the complaint!

**Comment by mikekryjak** [comment]
Thanks @ZedThree. I'm using the DLS for something right now and running with this branch. I wanted to get used to Ruff to be able to go through it properly.

**Review by mikekryjak — APPROVED** [review]
Looks great!

**Pull request merged**
